[project]
name = "21savage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "moondream>=0.1.1",
    "numpy>=2.2.3",
    "opencv-python>=4.12.0.88",
    "pydantic>=2.10.6",
    "pytesseract>=0.3.13",
    "python-dotenv>=1.0.1",
]
